#zuul路由的strip-prefix与order
server:
  port: 8040
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka #将eureka注册到url
      defaultZone: http://user:password@localhost:8761/eureka   #将eureka注册到url
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-gateway-zuul

