server:
  port: 8140
eureka:
  client:
    healthckeck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: microservice-consumer-movie-feign-hystrix

