server:
  port: 8081
user:
  userServicePath: http://peer3:8023/simple/
eureka:
  client:
    serviceUrl:
      #defaultZone: http://user:password@localhost:8761/eureka/
      defaultZone: http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: microservice-consumer-movie
