security:
  basic:
    enable: true
  user:
    name: user
    password: password2
server:
  port: 8761
eureka:
  client:
    #单机模拟，不用把本服务当成eureka client，只把它当作eureka server
    register-with-eureka: false
    fetch-registry: false

    service-url:
      #defaultZone: http://localhost:8761/eureka #将eureka注册到url
      defaultZone: http://user:password@localhost:8761/eureka #将eureka注册到url
