server:
  port: 8081
user:
  userServicePath: http://localhost:8080/simple/
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: microservice-consumer-movie
